openapi: 3.0.1
info:
  title: Catracker
  version: 0.1
  description: Catracker
paths:
  /ttnhttp:
    post:
      operationId: incomingEventTtn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/TTNEvent'
      responses:
        '201':
          description: Created
  /kpn:
    post:
      operationId: incomingEventKpn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/definitions/KPNEventRecord'
      responses:
        '201':
          description: Created
  /paths/{device}:
    get:
      operationId: pathForDevice
      parameters:
        - in: path
          name: device
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DevicePath'

servers:
  - url: http://host
components:
  schemas:
    DevicePath:
      type: object
      required:
        - description
        - positions
        - lastSeen
      properties:
        description:
          type: string
        lastSeen:
          type: number
        positions:
          type: array
          items:
            type: object
            required:
              - latitude
              - longitude
              - battery
            properties:
              latitude:
                type: number
                format: double
              longitude:
                type: number
                format: double
              battery:
                type: number
    KPNEventRecord:
      type: object
      properties:
        bn:
          type: string
        bt:
          type: number
        v:
          type: number
        vs:
          type: string
        n:
          type: string
    TTNEvent:
      type: object
      required:
        - end_device_ids
        - uplink_message
        - received_at
      properties:
        end_device_ids:
          type: object
          required:
            - device_id
            - application_ids
            - dev_eui
            - join_eui
            - dev_addr
          properties:
            device_id:
              type: string
            application_ids:
              type: object
              required:
                - application_id
              properties:
                application_id:
                  type: string
            dev_eui:
              type: string
            join_eui:
              type: string
            dev_addr:
              type: string
        correlation_ids:
          type: array
          items:
            type: string
        received_at:
          type: string
        uplink_message:
          type: object
          required:
            - decoded_payload
            - f_port
            - f_cnt
            - rx_metadata
            - settings
            - received_at
            - consumed_airtime
          properties:
            session_key_id:
              type: string
            f_port:
              type: integer
              format: int32
            f_cnt:
              type: integer
              format: int32
            frm_payload:
              type: string
            decoded_payload:
              type: object
              required:
                - accuracy
                - capacity
                - fix
                - latitude
                - longitude
                - temperature
                - voltage
              properties:
                accuracy:
                  type: integer
                  format: int32
                capacity:
                  type: number
                fix:
                  type: boolean
                latitude:
                  type: number
                  format: double
                longitude:
                  type: number
                  format: double
                temperature:
                  type: integer
                  format: int32
                voltage:
                  type: number
            rx_metadata:
              type: array
              items:
                type: object
                required:
                  - gateway_ids
                  - time
                  - timestamp
                  - rssi
                  - channel_rssi
                  - snr
                  - received_at
                  - uplink_token
                properties:
                  gateway_ids:
                    type: object
                    required:
                      - gateway_id
                      - eui
                    properties:
                      gateway_id:
                        type: string
                      eui:
                        type: string
                  time:
                    type: string
                  timestamp:
                    type: integer
                    format: int64
                  rssi:
                    type: integer
                    format: int32
                  channel_rssi:
                    type: integer
                    format: int32
                  snr:
                    type: number
                  uplink_token:
                    type: string
                  received_at:
                    type: string
                    format: date-time
            settings:
              type: object
              required:
                - data_rate
                - frequency
                - timestamp
              properties:
                data_rate:
                  type: object
                  required:
                    - loar
                  properties:
                    lora:
                      type: object
                      required:
                        - bandwidth
                        - spreading_factor
                        - coding_rate
                      properties:
                        bandwidth:
                          type: integer
                          format: int32
                        spreading_factor:
                          type: integer
                          format: int32
                        coding_rate:
                          type: string
                frequency:
                  type: string
                timestamp:
                  type: integer
                  format: int64
                time:
                  type: string
            received_at:
              type: string
              format: date-time
            consumed_airtime:
              type: string
            network_ids:
              type: object
              properties:
                net_id:
                  type: string
                tenant_id:
                  type: string
                cluster_id:
                  type: string
                cluster_address:
                  type: string

